default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stop_flattering_yourself_development
  username: bruno
  password:
  host: /var/run/postgresql

test:
  <<: *default
  database: stop_flattering_yourself_test
  username: bruno
  password:
  host: /var/run/postgresql

production:
  <<: *default
  database: stop_flattering_yourself_production
  username: stop_flattering_yourself
  password: <%= ENV["STOP_FLATTERING_YOURSELF_DATABASE_PASSWORD"] %>
